modLoader="javafml"
loaderVersion="${loader_version_range}"
# issueTrackerURL = "https://github.com/CrazyWoddMan/${project.name}/issues/"
license="MIT"

[[mods]]
	modId="${mod_id}"
	version="${mod_version}"
	displayName="${mod_name}"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/atelier"
    logoFile = "icon.png"
    credits="${credits}"
	authors="${mod_authors}"
	description='''${mod_description}'''
	mixins = "${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true 
    versionRange="[${forge_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[${mc_version}]"
    ordering="NONE"
    side="BOTH"
	
[[dependencies.${mod_id}]]
    modId="accessories"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"